### ISSUE TITLE
error on creation of user

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [maxplanck-ie/docker-parkour#6]
I use this command:
`
docker-compose run parkour-web python manage.py createsuperuser`

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 63, in execute
    return super(Command, self).execute(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 116, in handle
    username = self.get_input_data(self.username_field, input_msg, default_username)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 192, in get_input_data
    raw_value = input(message)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 8: invalid continuation byte
```

**Comment by dpryan79** [comment]
FYI, I can't reproduce this on Ubuntu 16.04.
